function writeAnim(camName, fileID, animID, t_max, position, orientation)
%% Write Animation
% This function writes an animation to an MDL file for use in _Star
% Wars(R): Knights of the Old Republic(TM)_ (_KotOR_).
%% Write Animation Header
header = sprintf([...
    'newanim CUT%03dW %s\n'...
    '  length %f\n'...
    '  transtime 0\n'...
    '  animroot %s\n'...
    'node dummy %s\n'...
    '  parent NULL\n'...
    'endnode\n'...
    'node dummy camerahook\n'...
    '  parent %s\n'],...
    animID, camName, t_max, camName, camName, camName);
fprintf(fileID, header);

%% Write Position Key
fprintf(fileID, 'positionkey\n');
writeKey(fileID, position);
fprintf(fileID, 'endlist\n');

%% Write Orientation Key
fprintf(fileID, 'orientationkey\n');
writeKey(fileID, orientation);
fprintf(fileID, 'endlist\n');

%% Write Animation Footer
footer = sprintf([...
    'endnode\n'...
    '\n'...
    'doneanim CUT%03dW %s\n'...
    '\n'],...
    animID, camName);
fprintf(fileID, footer);

end

